There are 2 ways to help us directly

1.- Go to INT.Store/YourDomain/Terminal and send money, we receive notification instantly and thank you very much for supporting

2.- Share the link INT.Store/YourDomain/Terminal with friends so they can see the digital tool we created for them

Thank you very much for being on this page!

Ricardo López Reyero
